export enum Errors {
  INVALID_PARAMETERS = 'INVALID_PARAMETERS',
  INVALID_ROUTE = 'INVALID_ROUTE',
}
export enum AuthErrors {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_LOGGED_IN = 'USER_NOT_LOGGED_IN',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  PASSWORD_NOT_THE_SAME = 'PASSWORD_NOT_THE_SAME',
}
